import {StyleSheet} from 'react-native';

const CharacterSheetStylesLight = StyleSheet.create({
  view: {
    height: '100%',
    width: '100%',
    overflow: 'hidden',
    backgroundColor: 'whitesmoke'
  },
  leftOverhang: {
    padding: 10,
    position: 'absolute',
    bottom: 50,
    right: -50,
    width: 50,
    height: 50,
    backgroundColor: 'white',
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    elevation: 6,
  },
  leftClose: {
    position: 'absolute',
    bottom: 50,
    left: 0,
    zIndex: 4,
    elevation: 8,
  },
  leftCloseBgr: {
    backgroundColor: 'white',
    borderRadius: 5,
    position: 'absolute',
    bottom: 50,
    width: 50,
    height: 50,
    left: 0,
    zIndex: 3,
    elevation: 8,
  },
  leftContent: {
    width: '110%',
    height: '100%',
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: 'white',
    borderTopRightRadius: 5,
    elevation: 6,
  },
  leftHeader: {
    position: 'absolute',
    top: 70,
    left: -30,
    width: '50%',
    elevation: 8,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    backgroundColor: 'white',
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 9,
    paddingRight: 20,
  },
  rightOverhang: {
    padding: 10,
    position: 'absolute',
    bottom: 50,
    left: -50,
    width: 50,
    height: 50,
    backgroundColor: 'white',
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    elevation: 6,
  },
  rightClose: {
    position: 'absolute',
    bottom: 50,
    right: 0,
    zIndex: 4,
    elevation: 8,
  },
  rightCloseBgr: {
    backgroundColor: 'white',
    borderRadius: 5,
    position: 'absolute',
    bottom: 50,
    width: 50,
    height: 50,
    right: 0,
    zIndex: 3,
    elevation: 8,
  },
  rightContent: {
    width: '110%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: 'white',
    borderTopLeftRadius: 5,
    elevation: 6,
    zIndex: 2,
  },
  rightHeader: {
    position: 'absolute',
    top: 70,
    right: -30,
    width: '50%',
    elevation: 9,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    backgroundColor: 'white',
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 10,
    paddingLeft: 20,
  },
  icon: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
});

const CharacterSheetStylesDark = StyleSheet.create({
  view: {
    height: '100%',
    width: '100%',
    overflow: 'hidden',
    backgroundColor: '#1d2630'
  },
  leftOverhang: {
    padding: 10,
    position: 'absolute',
    bottom: 50,
    right: -50,
    width: 50,
    height: 50,
    backgroundColor: '#263240',
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    elevation: 6,
  },
  leftClose: {
    position: 'absolute',
    bottom: 50,
    left: 0,
    zIndex: 4,
    elevation: 8,
  },
  leftCloseBgr: {
    backgroundColor: '#263240',
    borderRadius: 5,
    position: 'absolute',
    bottom: 50,
    width: 50,
    height: 50,
    left: 0,
    zIndex: 3,
    elevation: 8,
  },
  leftContent: {
    width: '110%',
    height: '100%',
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#263240',
    borderTopRightRadius: 5,
    elevation: 6,
  },
  leftHeader: {
    position: 'absolute',
    top: 70,
    left: -30,
    width: '50%',
    elevation: 8,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    backgroundColor: '#263240',
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 9,
    paddingRight: 20,
  },
  rightOverhang: {
    padding: 10,
    position: 'absolute',
    bottom: 50,
    left: -50,
    width: 50,
    height: 50,
    backgroundColor: '#263240',
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    elevation: 6,
  },
  rightClose: {
    position: 'absolute',
    bottom: 50,
    right: 0,
    zIndex: 4,
    elevation: 8,
  },
  rightCloseBgr: {
    backgroundColor: '#263240',
    borderRadius: 5,
    position: 'absolute',
    bottom: 50,
    width: 50,
    height: 50,
    right: 0,
    zIndex: 3,
    elevation: 8,
  },
  rightContent: {
    width: '110%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#263240',
    borderTopLeftRadius: 5,
    elevation: 6,
    zIndex: 2,
  },
  rightHeader: {
    position: 'absolute',
    top: 70,
    right: -30,
    width: '50%',
    elevation: 9,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    backgroundColor: '#263240',
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 10,
    paddingLeft: 20,
  },
  icon: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
});

const CharacterSheetStyles = (mode) => {
    if (mode === Mode.dark) {
        return CharacterSheetStylesDark;
    } else {
        return CharacterSheetStylesLight;
    }
};

const Mode = {
    dark: 'dark',
    light: 'light',
};

export {CharacterSheetStyles, Mode};
