import {StyleSheet} from 'react-native';

const CharacterSheetStyles = StyleSheet.create({
  view: {
    height: '100%',
    width: '100%',
    overflow: 'hidden',
    backgroundColor: 'whitesmoke'
  },
  leftOverhang: {
    padding: 10,
    position: 'absolute',
    bottom: 50,
    right: 0,
    backgroundColor: 'white',
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    elevation: 7,
  },
  leftClose: {
    backgroundColor: 'white',
    borderRadius: 5,
    position: 'absolute',
    bottom: 50,
    left: 0,
    zIndex: 1,
    elevation: 9,
  },
  leftContent: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    right: '10%',
    backgroundColor: 'white',
    borderTopRightRadius: 5,
    elevation: 7,
  },
  leftHeader: {
    position: 'absolute',
    top: 70,
    left: -30,
    width: '90%',
    elevation: 9,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    backgroundColor: 'white',
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 9,
    paddingRight: 20,
  },
  rightOverhang: {
    padding: 10,
    position: 'absolute',
    bottom: 50,
    left: 0,
    backgroundColor: 'white',
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    elevation: 7,
  },
  rightClose: {
    backgroundColor: 'white',
    borderRadius: 5,
    position: 'absolute',
    bottom: 50,
    right: 0,
    zIndex: 1,
    elevation: 9,
  },
  rightContent: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: '10%',
    backgroundColor: 'white',
    borderTopLeftRadius: 5,
    elevation: 7,
  },
  rightHeader: {
    position: 'absolute',
    top: 70,
    right: -30,
    width: '90%',
    elevation: 9,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    backgroundColor: 'white',
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 10,
    paddingLeft: 20,
  },
  icon: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
});

export default CharacterSheetStyles;
